name: Atualizar Badges do Perfil

on:
  schedule:
    - cron: '0 */6 * * *'  # A cada 6 horas
  workflow_dispatch:

jobs:
  update-profile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Gerar badges dinâmicos
        uses: brunosillvax/github-dyno-badges@v1.0.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}