name: Update Profile

on:
  schedule:
    - cron: '0 */6 * * *'  # A cada 6 horas
  workflow_dispatch:  # Execução manual

jobs:
  update-profile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Update profile with Dyno-Badges
        uses: brunosillvax/github-dyno-badges@v1.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
